/// File: lib/firebase_options.dart
/// Role: Auto-generated configuration file by FlutterFire CLI.
/// Provides default FirebaseOptions for different platforms (Android, iOS, macOS, Windows, Web).

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Resolves the current platform and returns the matching [FirebaseOptions].
  ///
  /// Throws an [UnsupportedError] if the current platform is linux or is not supported.
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Evaluates target platforms at runtime to select the correct keys and application IDs configured in Firebase console.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Firebase options configuration specifically for the Web platform.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9kjoBzDkcmFa9nzcwQvvxYcbbyWfyqBM',
    appId: '1:606873051540:web:21acc9f022c5bee333af81',
    messagingSenderId: '606873051540',
    projectId: 'tunein-921b4',
    authDomain: 'tunein-921b4.firebaseapp.com',
    storageBucket: 'tunein-921b4.firebasestorage.app',
    measurementId: 'G-VVCJKHB65Q',
  );

  /// Firebase options configuration specifically for the Android platform.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC19PkTmQbR0KXxNNUDa03dV4dIa7Nn3FQ',
    appId: '1:606873051540:android:0d305160b7275abb33af81',
    messagingSenderId: '606873051540',
    projectId: 'tunein-921b4',
    storageBucket: 'tunein-921b4.firebasestorage.app',
  );

  /// Firebase options configuration specifically for the iOS platform.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCc8yQP34DwSrpkkmGO2CiKXhy5uQOeQM',
    appId: '1:606873051540:ios:b1b68da76936599733af81',
    messagingSenderId: '606873051540',
    projectId: 'tunein-921b4',
    storageBucket: 'tunein-921b4.firebasestorage.app',
    iosBundleId: 'com.example.tunely',
  );

  /// Firebase options configuration specifically for the macOS platform.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCc8yQP34DwSrpkkmGO2CiKXhy5uQOeQM',
    appId: '1:606873051540:ios:b1b68da76936599733af81',
    messagingSenderId: '606873051540',
    projectId: 'tunein-921b4',
    storageBucket: 'tunein-921b4.firebasestorage.app',
    iosBundleId: 'com.example.tunely',
  );

  /// Firebase options configuration specifically for the Windows platform.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9kjoBzDkcmFa9nzcwQvvxYcbbyWfyqBM',
    appId: '1:606873051540:web:4b416a91addd659e33af81',
    messagingSenderId: '606873051540',
    projectId: 'tunein-921b4',
    authDomain: 'tunein-921b4.firebaseapp.com',
    storageBucket: 'tunein-921b4.firebasestorage.app',
    measurementId: 'G-N6083KM6T7',
  );
}
